# -*- mode: python ; coding: utf-8 -*-

block_cipher = None
#注意运行C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts\pyinstaller.exe pyinstaller.novalide.python.debug.spec的时候不能在编辑器里面打开的终端中操作
#必须在操作文件系统里面打开终端

#程序数据文件列表,第一列表示源文件路径,第二列表示目的相对路径
datas = [
    ("noval.ico","./"),
    ("version.txt","./"),
    ("template.xml","./"),
    ("requirements.txt","./"),
    ("./dist/Analyzer/analyzer.exe","./"),
    ("novalapp/syntax/lexer/*.py","novalapp/syntax/lexer"),
    ("novalapp/python/syntax/lexer/*.py","novalapp/python/syntax/lexer"),
    #这里必须用*.*通配符否则会把所有子目录的图片都放在根目录下,*表示所有子文件以及目录
    ("novalapp/bmp_source/*.*","novalapp/bmp_source"),
    ("novalapp/bmp_source/mdviewer/*.*","novalapp/bmp_source/mdviewer"),
    ("novalapp/bmp_source/project/*","novalapp/bmp_source/project"),
    ("novalapp/bmp_source/project/template/*","novalapp/bmp_source/project/template"),
    ("novalapp/bmp_source/project/python/template/*","novalapp/bmp_source/project/python/template"),
    ("novalapp/bmp_source/project/python/*.*","novalapp/bmp_source/project/python"),
    ("novalapp/bmp_source/file/*","novalapp/bmp_source/file"),
    ("novalapp/bmp_source/files/*","novalapp/bmp_source/files"),
    ("novalapp/bmp_source/toolbar/*","novalapp/bmp_source/toolbar"),
    ("novalapp/bmp_source/web/*.png","novalapp/bmp_source/web"),
    ("novalapp/bmp_source/python/autocmp/*.png","novalapp/bmp_source/python/autocmp"),
    ("novalapp/bmp_source/python/symbol/*.*","novalapp/bmp_source/python/symbol"),
    ("novalapp/bmp_source/python/outline/*","novalapp/bmp_source/python/outline"),
    ("novalapp/bmp_source/python/*.*","novalapp/bmp_source/python"),
    ("novalapp/bmp_source/python/debugger/*","novalapp/bmp_source/python/debugger"),
    ("novalapp/data/feeds.json","novalapp/data"),
    ("novalapp/data/template/*.tar.bz2","novalapp/data/template"),
    ("novalapp/data/sample/*.sample","novalapp/data/sample"),
    ("novalapp/data/skins/README.md","novalapp/data/skins"),
    ("novalapp/data/skins/green-black/*.*","novalapp/data/skins/green-black"),
    ("novalapp/data/skins/light/*.*","novalapp/data/skins/light"),
    ("novalapp/data/syntax/themes/default_dark/*.*","novalapp/data/syntax/themes/default_dark"),
    ("novalapp/data/syntax/themes/default_dark_blue/*.*","novalapp/data/syntax/themes/default_dark_blue"),
    ("novalapp/data/syntax/themes/default_dark_green/*.*","novalapp/data/syntax/themes/default_dark_green"),
    ("novalapp/data/syntax/themes/default_light/*.*","novalapp/data/syntax/themes/default_light"),
    ("novalapp/data/syntax/themes/idle_classic/*.*","novalapp/data/syntax/themes/idle_classic"),
    ("novalapp/data/syntax/themes/idle_dark/*.*","novalapp/data/syntax/themes/idle_dark"),
    ('novalapp/locale/en_US/LC_MESSAGES/*.mo',"novalapp/locale/en_US/LC_MESSAGES"),
    ('novalapp/locale/zh_CN/LC_MESSAGES/*.mo',"novalapp/locale/zh_CN/LC_MESSAGES"),
    ("novalapp/python/explain.py","novalapp/python"),
    ("novalapp/python/prog_lang_ext.py","novalapp/python"),
    ("novalapp/python/parser/builtin_types.py","novalapp/python/parser"),
    ("novalapp/python/parser/pyd_builtins.py","novalapp/python/parser"),
    ("novalapp/python/parser/objtypes.py","novalapp/python/parser"),
    ("novalapp/python/parser/define.py","novalapp/python/parser"),
    ("novalapp/python/apis/iconid.py","novalapp/python/apis"),
    ("novalapp/python/apis/memberkeys.py","novalapp/python/apis"),
    ("novalapp/plugins/*.py","novalapp/plugins"),
    ("novalapp/backend/*.py","novalapp/backend"),
    ("novalapp/python/plugins/*.py","novalapp/python/plugins"),
    ("novalapp/python/plugins/pyshell/*.py","novalapp/python/plugins/pyshell"),
    ('novalapp/python/debugger/debuggerharness.py','novalapp/python/debugger'),
    ("novalapp/plugins/printer/*.*","novalapp/plugins/printer"),
    ("novalapp/plugins/mdviewer/*.*","novalapp/plugins/mdviewer"),
    ("C:\\Users\\HongYunVM\\AppData\\Local\\Programs\\Python\\Python311\\Doc\\*", "Doc/html"),
    ("C:\\dev\\venv\\Lib\\site-packages\\text_unidecode\\data.bin", "./text_unidecode")
]

hidden_imports=[
	'novalapp.python.editor',
	'novalapp.common.md5',
	'novalapp.project.processor',
	'platformdirs',
	'novalapp.syntax.syndata',
	'novalapp.sidebar.outline',
	'novalapp.project.property.resource',
	'novalapp.python.project.property.debugrun',
	'novalapp.python.project.property.interpreter',
	'novalapp.python.project.property.referrence',
	'novalapp.python.project.property.pythonpath',
	'novalapp.python.debugger.sideview',
	'novalapp.debugger.tracer',
	'mistune',
	'mistune.plugins.formatting',
	'mistune.plugins.footnotes',
	'mistune.plugins.table',
	'mistune.plugins.speedup',
    'slugify',
    'text_unidecode'
]
a = Analysis(['novalide.py'],
             pathex=[
		'C:\\codimension\\venv\\Lib\\site-packages\\qdarkstyle-2.8.1-py3.11.egg',
		'./novalapp./python./thirdparty',
		'C:\\dev\\venv\\Lib\\site-packages'
	     ],
             binaries=[],
             datas=datas,
             hiddenimports=hidden_imports,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
#console为True表示控制台界面
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='NovalIDE',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False , icon='./noval.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='NovalIDE')
